# Generated by Django 5.1.4 on 2025-01-24 08:16

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Business Name', help_text='Title for the business.', max_length=255)),
                ('header_text', models.TextField(blank=True, help_text='Text displayed in the header section.', null=True)),
                ('header_image', cloudinary.models.CloudinaryField(blank=True, help_text='Background image for the header.', max_length=255, null=True, verbose_name='image')),
                ('business_description', models.TextField(blank=True, help_text='Description of the business.', null=True)),
                ('business_image', cloudinary.models.CloudinaryField(blank=True, help_text='Business overview image.', max_length=255, null=True, verbose_name='image')),
                ('footer_email', models.EmailField(blank=True, help_text='Contact email for the business.', max_length=254, null=True)),
                ('footer_phone', models.CharField(blank=True, help_text='Contact phone number.', max_length=20, null=True)),
                ('footer_location', models.CharField(default='', max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person giving feedback.', max_length=100)),
                ('feedback', models.TextField(help_text='Feedback content.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='landingPage.landingpage')),
            ],
        ),
    ]
