# Generated by Django 5.1.5 on 2025-01-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0002_landingpage_user_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('landing_page_id', models.IntegerField()),
            ],
        ),
    ]
