# Generated by Django 5.1.5 on 2025-01-26 19:17

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0003_landingpagelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessCardName', models.CharField(blank=True, max_length=225, null=True)),
                ('businessCardImage', cloudinary.models.CloudinaryField(blank=True, help_text='Business card image', max_length=255, null=True, verbose_name='image')),
                ('email', models.EmailField(blank=True, help_text='Business card email', max_length=254, null=True, unique=True)),
                ('businessCardDescription', models.TextField(blank=True, help_text='Business card description', null=True)),
                ('LandingPageLink', models.OneToOneField(help_text='Associated landing page', on_delete=django.db.models.deletion.CASCADE, related_name='business_card', to='landingPage.landingpage')),
            ],
        ),
    ]
