# Generated by Django 5.1.5 on 2025-01-26 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0004_businesscard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessCard',
        ),
    ]
