# Generated by Django 5.1.5 on 2025-01-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0005_delete_businesscard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='header_image',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='header_text2',
            field=models.TextField(blank=True, help_text='header text 2.', null=True),
        ),
    ]
