# Generated by Django 5.1.5 on 2025-02-04 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0007_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='feedback',
        ),
    ]
