# Generated by Django 5.1.4 on 2025-01-24 08:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.TextField()),
                ('product_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('product_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
