# Generated by Django 5.1.5 on 2025-01-27 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0006_remove_landingpage_header_image_and_more'),
        ('products', '0002_product_category_product_email_product_professional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='landingPage.landingpage'),
        ),
    ]
